name: qr_code_generator_scanner
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  flutter_svg: ^1.1.3

  # barcode generator
  barcode: ^2.2.2

  # barcode scanner
  mobile_scanner: ^2.0.0 # android-ios-macos-web

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # to build windows msix
  msix: ^3.6.3

  # to build linux debian
  flutter_to_debian: ^1.0.3

flutter:
  uses-material-design: true

msix_config:
  display_name: QR Code Generator
  publisher_display_name: Company Name
  identity_name: company.suite.flutterapp
  msix_version: 1.0.0.0
  logo_path: windows\runner\resources\app_icon.ico